name: Update README

on:
  push:
    branches:
      - main  # Adjust this according to your main branch name
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust Python version as needed

      - name: Install dependencies
        run: |
          pip install gha-github-contributions  # Install the tool to generate the commit frequency table

      - name: Generate commit frequency table
        run: |
          gha-github-contributions --output README.md  # Generate the commit frequency table and save it to README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update commit frequency table [skip ci]"
          git push
